name: passmgr_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # tus dependencias
  cupertino_icons: ^1.0.2
  path_provider:    ^2.0.15
  google_sign_in:   ^5.0.0
  googleapis:       ^11.0.0
  flutter_secure_storage: ^8.0.0
  local_auth:       ^2.1.0
  sqflite_sqlcipher: ^2.0.0
  cryptography:     ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true